Fix mirte_teleop

diff --git a/.github/workflows/catkin-lint.yml b/.github/workflows/catkin-lint.yml
--- a/.github/workflows/catkin-lint.yml
+++ b/.github/workflows/catkin-lint.yml
@@ -1,4 +1,4 @@
-name: Catkin_lint ros style check
+name: Compile and catkin_lint ros style check
 on: [push, pull_request]
 jobs:
   check_ros_style:
@@ -6,7 +6,7 @@ jobs:
     container:
       image: ros:noetic
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
       - run: apt update && apt install catkin-lint -y
       - run: |
           mkdir -p catkin_ws/src
@@ -27,11 +27,12 @@ jobs:
       - run: |
           . catkin_ws/devel/setup.sh
           failure=false
-          catkin_lint --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_bringup || failure=true
-          catkin_lint --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_control || failure=true
-          catkin_lint --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_msgs || failure=true
-          catkin_lint --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_telemetrix || failure=true
-          catkin_lint --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_teleop || failure=true
+          # Run all tests before failing to test all packages
+          catkin_lint --strict --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_bringup || failure=true
+          catkin_lint --strict --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_control || failure=true
+          catkin_lint --strict --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_msgs || failure=true
+          catkin_lint --strict --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_telemetrix || failure=true
+          catkin_lint --strict --explain --ignore uninstalled_target --ignore uninstalled_script --pkg mirte_teleop || failure=true
           if $failure; then
               echo "Automated tests failed" >&2
           exit 1
